if(EXISTS "/Users/stevenquadros/code/cmaketut/hello_test[1]_tests.cmake")
  include("/Users/stevenquadros/code/cmaketut/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
